---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: backstage-credentials
  namespace: backstage
spec:
  length: 24
  secretTemplate:
    type: Opaque
    stringData:
      BACKSTAGE_BACKEND_SECRET: $(value)
