---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgresl-admin-password
  namespace: backstage
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      admin-password: $(value)

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgresl-user-password
  namespace: backstage
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      user-password: $(value)

---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgresl-replication-password
  namespace: backstage
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      replication-password: $(value)

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: postgresql-credentials
  namespace: backstage
spec:
  inputResources:
    - name: admin
      ref:
        apiVersion: v1
        kind: Secret
        name: postgresl-admin-password
    - name: user
      ref:
        apiVersion: v1
        kind: Secret
        name: postgresl-user-password
    - name: replication
      ref:
        apiVersion: v1
        kind: Secret
        name: postgresl-replication-password
  template:
    data:
      admin-password: $(.admin.data.admin-password)
      user-password: $(.user.data.user-password)
      replication-password: $(.replication.data.replication-password)
